config_version: "1.0"
rng_strategy: RngStream
individuals: 1e5
race: 0
sex: 0
cohort_year: 2010
number_of_segments: 4
seeds:
  - 12345
  - 12345
  - 12345
  - 12345
  - 12345
  - 12345
params:
  smok_params_source: tests/testdata/usa-national@smok-NHIS-2018.zip
  mort_params_source: tests/testdata/usa-national@mort-v1.0.0.zip
  mort_params_type: acm
