// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// smokinghistorygenerator
bool smokinghistorygenerator(const char* sInputFileName);
RcppExport SEXP _RcppSmokingHistoryGenerator_smokinghistorygenerator(SEXP sInputFileNameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const char* >::type sInputFileName(sInputFileNameSEXP);
    rcpp_result_gen = Rcpp::wrap(smokinghistorygenerator(sInputFileName));
    return rcpp_result_gen;
END_RCPP
}
// RunWebVersion
int RunWebVersion(const char * sInputFileName);
RcppExport SEXP _RcppSmokingHistoryGenerator_RunWebVersion(SEXP sInputFileNameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const char * >::type sInputFileName(sInputFileNameSEXP);
    rcpp_result_gen = Rcpp::wrap(RunWebVersion(sInputFileName));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RcppSmokingHistoryGenerator_smokinghistorygenerator", (DL_FUNC) &_RcppSmokingHistoryGenerator_smokinghistorygenerator, 1},
    {"_RcppSmokingHistoryGenerator_RunWebVersion", (DL_FUNC) &_RcppSmokingHistoryGenerator_RunWebVersion, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_RcppSmokingHistoryGenerator(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
