# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' SHGInterface Class
#' @name SHGInterface
#' @title SHGInterface
#' @aliases SHGInterface
#' @export
#' @description The SHG Interface class provides an Rcpp interface to the Smoking History Generator (SHG)
#' @field number_of_segments Number of segments to use for single or multi-threaded simulation (default is 1)
#' @field run_multi_threaded True if the simulation should be run asynchonously; False otherwise (default is False)
#' @field rng_strategy 'RngStream' for MRG32k3a (default) or 'MersenneTwister' for Mersenne Twister RNG. 'RngStream' is recommended for reproducibility especially with multi-threaded simulations.
#' @field input_data_folder Set or get the base folder for input data files
#' @field initiation_filename Set or get the initiation filename
#' @field cessation_filename Set or get the cessation filename
#' @field lifetable_filename Set or get the lifetable filename
#' @field cpd_filename Set or get the cpd filename
#' @field immediate_cessation_year Set or get Immediate Cessation Year; If 0, no immediate cessation
NULL

#' @name runSimFromDataFrame
#' @title runSimFromDataFrame method
#' @description runSimFromDataFrame offers a way to configure and run a simulation from an existing R dataframe. It returns a dataframe of simulated smoking histories with the same number of rows and order as the input dataframe.
#' @param dfPopulation The input dataframe with named columns for race, sex, and birth_cohort
#' @examples
#' \dontrun{
#' library(RcppSmokingHistoryGenerator)
#' shg <- new(SHGInterface)
#' print(system.file("inputs/default", "", package="RcppSmokingHistoryGenerator"))
#' shg$input_data_folder <- system.file("inputs/default", "", package="RcppSmokingHistoryGenerator")
#' N <- 10^6
#' pop <- list(
#'     race = rep(0, N),
#'     sex = sample(x = c(0, 1), size = N, prob = c(0.5, 0.5), replace = TRUE),
#'     birth_cohort = rep(1930:1949, N / 20)
#' )
#' shg$rng_strategy <- "RngStream"
#' shg$number_of_segments <- 10
#' shg$run_multi_threaded <- TRUE
#' smoking_history <- shg$runSimFromDataFrame(pop)
#' }
NULL

#' @name runSimFromFixedValues
#' @title runSimFromFixedValues method
#' @description runSimFromFixedValues offers a way to configure and run a simulation from fixed values for race, sex, and birth year cohort rather than passing a data frame. It returns a dataframe of simulated smoking histories for n individuals.
#' @param repeat The number of individuals to simulate
#' @param race (default = 0 and refers to all races combined)
#' @param sex (0 for male, 1, for female)
#' @param cohort_year (four digit birth cohort year)
#' @examples
#' library(RcppSmokingHistoryGenerator)
#'
#' shg <- new(SHGInterface)
#' shg$input_data_folder <- system.file("inputs/default", "", package="RcppSmokingHistoryGenerator")
#' N <- 10^6
#' smoking_history <- shg$runSimFromFixedValues(N, 0, 0, 1950)
NULL

#' @name LegacyRunWebVersion
#' @title LegacyRunWebVersion method
#' @description This method offers a way to configure and run a simulation from an input configuration file. Rather than return a R DataFrame, it produces results in an output file. It works in the same as calling the CLI version of the Smoking History Generator with a single input file parameter.
#' @param input_file_name The name of the configuration file (see ./inst/inputs/ for 2 examples)
#' @examples
#' # Warning: This way of running a simulation ignores the Rcpp interface properties and relies soley 
#' # on parameters set in the input configuration file. See main.cpp's RunWebVersion for more detail.
#' library(RcppSmokingHistoryGenerator)
#' shg <- new(SHGInterface)
#' shg$input_data_folder <- system.file("inputs/default", "", package="RcppSmokingHistoryGenerator")
#' example_input_filepath <- system.file("inputs/examples/", "test_input_example_MersenneTwister.txt", package="RcppSmokingHistoryGenerator")
#' shg$LegacyRunWebVersion(example_input_filepath)
NULL

#' Rcpp SHG Interface Class
#' @name Rcpp_SHGInterface
#' @title Rcpp SHG Interface Class
#' @export
#' @description This module provides an Rcpp interface to the Smoking History Generator (SHG) application.
NULL

