# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' SHGInterface Class
#' @name SHGInterface
#' @title SHGInterface
#' @aliases SHGInterface
#' @export
#' @description The SHG Interface class provides an Rcpp interface to the Smoking History Generator (SHG)
#' @field number_of_segments Number of segments to use for simulation. Use -1 for auto-calculation (default), 1 for single segment, or N > 1 for explicit segment count. Auto-calculation uses: min(cores * 10, repeat / 1000). Note: MersenneTwister RNG is restricted to 1 segment.
#' @field num_threads Thread count: -1 = auto (all cores, multi-threaded), 1 = single-threaded, N = use N threads. Default: -1. Note: MersenneTwister RNG requires num_threads = 1.
#' @field rng_strategy 'RngStream' for MRG32k3a (default) or 'MersenneTwister' for Mersenne Twister RNG. 'RngStream' is recommended for reproducibility especially with multi-threaded simulations. Note: MersenneTwister RNG is restricted to single-segment, non-parallel execution due to limitations in maintaining IID properties across segments.
#' @field input_data_folder Set or get the base folder for input data files
#' @field initiation_filename Set or get the initiation filename
#' @field cessation_filename Set or get the cessation filename
#' @field lifetable_filename Set or get the lifetable filename
#' @field cpd_filename Set or get the cpd filename
#' @field immediate_cessation_year Set or get Immediate Cessation Year; If 0, no immediate cessation
#' @field mt_seeds Set or get MersenneTwister seeds. Must be a numeric vector of exactly 4 values (one for each stream: initiation, cessation, life table, individual). If not set, default seeds are used. Only used when rng_strategy is "MersenneTwister".
#' @field rngstream_seed Set or get RngStream seed. Must be a numeric vector of exactly 6 values (a single seed vector that generates 4 substreams, one for each stream: initiation, cessation, life table, individual). If not set, default seed is used. Only used when rng_strategy is "RngStream".
NULL

#' @name runSimFromDataFrame
#' @title runSimFromDataFrame method
#' @description runSimFromDataFrame offers a way to configure and run a simulation from an existing R dataframe. It returns a dataframe of simulated smoking histories with the same number of rows and order as the input dataframe.
#' @param dfPopulation The input dataframe with named columns for race, sex, and birth_cohort
#' @examples
#' \dontrun{
#' library(SmokingHistoryGenerator)
#' shg <- new(SHGInterface)
#' shg$input_data_folder <- system.file("inputs/default", "", package="SmokingHistoryGenerator")
#' N <- 10^6
#' pop <- list(
#'     race = rep(0, N),
#'     sex = sample(x = c(0, 1), size = N, prob = c(0.5, 0.5), replace = TRUE),
#'     birth_cohort = rep(1930:1949, N / 20)
#' )
#' shg$rng_strategy <- "RngStream"
#' # Optionally set a custom seed for RngStream (6 values)
#' shg$rngstream_seed <- c(12345, 12345, 12345, 12345, 12345, 12345)
#' shg$number_of_segments <- -1 # auto-calculate (default), or set explicit value for reproducibility
#' shg$num_threads <- -1  # -1 = auto (all cores), 1 = single-threaded
#' smoking_history <- shg$runSimFromDataFrame(pop)
#' 
#' # Example with MersenneTwister and custom seeds (4 values)
#' shg2 <- new(SHGInterface)
#' shg2$input_data_folder <- system.file("inputs/default", "", package="SmokingHistoryGenerator")
#' shg2$rng_strategy <- "MersenneTwister"
#' shg2$mt_seeds <- c(1898587603, 1468371936, 1551308340, 1590227640)
#' smoking_history2 <- shg2$runSimFromFixedValues(1000, 0, 0, 1950)
#' }
NULL

#' @name runSimFromFixedValues
#' @title runSimFromFixedValues method
#' @description runSimFromFixedValues offers a way to configure and run a simulation from fixed values for race, sex, and birth year cohort rather than passing a data frame. It returns a dataframe of simulated smoking histories for n individuals.
#' @param repeat The number of individuals to simulate
#' @param race (default = 0 and refers to all races combined)
#' @param sex (0 for male, 1, for female)
#' @param cohort_year (four digit birth cohort year)
#' @examples
#' \dontrun{
#' library(SmokingHistoryGenerator)
#' shg <- new(SHGInterface)
#' shg$input_data_folder <- system.file("inputs/default", "", package="SmokingHistoryGenerator")
#' N <- 10^6
#' smoking_history <- shg$runSimFromFixedValues(N, 0, 0, 1950)
#' }
NULL

#' @name LegacyRunWebVersion
#' @title LegacyRunWebVersion method
#' @description This method offers a way to configure and run a simulation from an input configuration file. Rather than return a R DataFrame, it produces results in an output file. It works in the same as calling the CLI version of the Smoking History Generator with a single input file parameter.
#' @param input_file_name The name of the configuration file (see ./inst/inputs/ for 2 examples)
#' @examples
#' \dontrun{
#' # Warning: This way of running a simulation ignores the Rcpp interface
#' # properties and relies solely on parameters set in the input configuration
#' # file. See main.cpp's RunWebVersion for more detail.
#' library(SmokingHistoryGenerator)
#' shg <- new(SHGInterface)
#' shg$input_data_folder <- system.file(
#'   "inputs/default", "", package = "SmokingHistoryGenerator"
#' )
#' example_input_filepath <- system.file(
#'   "inputs/examples/", "test_input_example_MersenneTwister.txt",
#'   package = "SmokingHistoryGenerator"
#' )
#' shg$LegacyRunWebVersion(example_input_filepath)
#' }
NULL

#' Rcpp SHG Interface Class
#' @name Rcpp_SHGInterface
#' @title Rcpp SHG Interface Class
#' @export
#' @description This module provides an Rcpp interface to the Smoking History Generator (SHG) application.
NULL

