# Roxygen blocks for Rcpp-exported methods (not regenerated by compileAttributes).

#' @name SHGInterface
#' @return An \code{SHGInterface} reference object (R6-style external pointer) wrapping the C++
#'   simulation engine. Configure fields, then call simulation methods such as
#'   \code{\link{runSimFromFixedValues}} or \code{\link{runSimFromDataFrame}}; use
#'   \code{\link{getConfig}} / \code{\link{useConfig}} for settings and
#'   \code{\link{shg_load_params}} (via \code{load_params()}) for parameter bundles.
NULL

#' @name Rcpp_SHGInterface
#' @return The exported reference class \code{SHGInterface} (see \code{\link{SHGInterface}}):
#'   an external pointer to the C++ engine used for all simulations.
NULL

#' @name get_data_shape
#' @return A named list describing loaded parameter tables: counts of races, sexes,
#'   and cohorts; age ranges for initiation, cessation, mortality, and CPD; mortality
#'   calendar years; CPD intensity groups; and CPD row load/skip counts. Intended for
#'   validation before running simulations.
NULL

#' @name runSimFromDataFrame
#' @return By default, a \code{data.frame} with one row per input individual (same order)
#'   and columns \code{smoking_initiation_age} (\code{-999} = never smoker),
#'   \code{smoking_cessation_age}, \code{age_at_death}, and \code{cigarettes_per_day}
#'   (character intensity codes). Constant \code{race}, \code{sex}, or
#'   \code{birth_cohort} are omitted when uniform. With \code{attach_run_info = TRUE},
#'   a list with \code{results}, \code{original_config}, \code{repro_config}, and
#'   \code{run_info}.
NULL

#' @name runSimFromFixedValues
#' @return By default, a \code{data.frame} of \code{repeat} simulated individuals with
#'   columns \code{smoking_initiation_age} (\code{-999} = never smoker),
#'   \code{smoking_cessation_age}, \code{age_at_death}, and \code{cigarettes_per_day}.
#'   With \code{attach_run_info = TRUE}, a list with \code{results},
#'   \code{original_config}, \code{repro_config}, and \code{run_info}.
NULL

#' @name LegacyRunWebVersion
#' @return No return value. Called for side effects: runs the CLI-style engine and writes
#'   semicolon-separated results to \code{OUTPUTFILE} and diagnostics to \code{ERRORFILE}
#'   as specified in the configuration file (properties on the R object are ignored).
NULL

#' @name useConfig
#' @return No return value. Called for side effects: updates fields on the \code{SHGInterface}
#'   instance to match \code{config} (typically from \code{\link{getConfig}}).
NULL
